import type { FastifyInstance } from 'fastify';
import { registerUploadRoutes } from './upload';
import { registerDetailRoutes } from './detail';
import { registerPageOperationsRoutes } from './page-operations';
import { registerRegenerateRoutes } from './regenerate';
import { registerAdminRoutes } from './admin';
import { registerDeleteRoutes } from './delete';
import { registerObservabilityRoutes } from './observability';
import { registerSyncRoutes } from './sync';
import { registerQuizRoutes } from './quizzes';
import { registerHandoutRoutes } from './handout';
import { registerExportRoutes } from './export';
import { registerImportRoutes } from './import';
import { registerAddPagesRoutes } from './add-pages';
import { registerDrawingsRoutes } from './drawings';
import { registerVersioningRoutes } from './versioning';
import { registerPageAnimationRoutes } from './page-animation';
import { registerFigureRoutes } from './figures';
import { registerRunHistoryRoutes } from './runs';
import { registerSlowArtifactRoutes } from './slow-artifacts';
import { registerSlaSettingsRoutes } from './sla-settings';
import { registerSkillRoutes } from './skills';
import { registerWatchProgressRoutes } from './watchProgress';
import { registerReportRoutes } from './report';
import { registerSubtitleRoutes } from './subtitles';
import { registerSearchRoutes } from './search';
import { registerQualityCheckRoutes } from './quality-check';
import { registerMonthlyCostRoutes } from './monthly-cost';
import { registerPptxRoutes } from './pptx';
import { registerCoursePackageRoutes } from './course-package';
import { registerQuizResultsCsvRoutes } from './quiz-results-csv';
import { registerReportAiSuggestionsRoutes } from './report-ai-suggestions';
import { registerScriptsTxtRoutes } from './scripts-txt';
import { registerNotesTxtRoutes } from './notes-txt';
import { registerGeneratePollRoutes } from './generate-poll';
import { registerBatchExportRoutes } from './batch-export';
import { registerPollResultsCsvRoutes } from './poll-results-csv';
import { registerGenerateQuizQuestionRoutes } from './generate-quiz-question';
import { registerCommentsRoutes } from './comments';
import { registerScormRoutes } from './scorm';
import { registerScriptQualityRoutes } from './script-quality';
import { registerH5pRoutes } from './h5p';
import { registerFromPagesRoutes } from './from-pages';
import { registerImageQualityRoutes } from './image-quality';
import { registerTemplateRoutes } from './templates';
import { registerEmbeddingStatsRoutes } from './embedding-stats';

export async function pdfRoutes(app: FastifyInstance): Promise<void> {
  await registerUploadRoutes(app);
  await registerDetailRoutes(app);
  await registerDeleteRoutes(app);
  await registerPageOperationsRoutes(app);
  await registerRegenerateRoutes(app);
  await registerAdminRoutes(app);
  await registerObservabilityRoutes(app);
  await registerSyncRoutes(app);
  await registerQuizRoutes(app);
  await registerHandoutRoutes(app);
  await registerExportRoutes(app);
  await registerImportRoutes(app);
  await registerAddPagesRoutes(app);
  await registerDrawingsRoutes(app);
  await registerVersioningRoutes(app);
  await registerPageAnimationRoutes(app);
  await registerFigureRoutes(app);
  await registerRunHistoryRoutes(app);
  await registerSlowArtifactRoutes(app);
  await registerSlaSettingsRoutes(app);
  await registerSkillRoutes(app);
  await registerWatchProgressRoutes(app);
  await registerReportRoutes(app);
  await registerSubtitleRoutes(app);
  await registerSearchRoutes(app);
  await registerQualityCheckRoutes(app);
  await registerMonthlyCostRoutes(app);
  await registerPptxRoutes(app);
  await registerCoursePackageRoutes(app);
  await registerQuizResultsCsvRoutes(app);
  await registerReportAiSuggestionsRoutes(app);
  await registerScriptsTxtRoutes(app);
  await registerNotesTxtRoutes(app);
  await registerGeneratePollRoutes(app);
  await registerBatchExportRoutes(app);
  await registerPollResultsCsvRoutes(app);
  await registerGenerateQuizQuestionRoutes(app);
  await registerCommentsRoutes(app);
  await registerScormRoutes(app);
  await registerScriptQualityRoutes(app);
  await registerH5pRoutes(app);
  await registerFromPagesRoutes(app);
  await registerImageQualityRoutes(app);
  await registerTemplateRoutes(app);
  await registerEmbeddingStatsRoutes(app);
}
