import { execFile as execFileCb } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { promisify } from 'node:util';
import { pdfDir } from './storage';
import { logger } from '../logger';

const execFile = promisify(execFileCb);

const GIT_USER_NAME = 'makeslide';
const GIT_USER_EMAIL = 'makeslide@local';

// Only exclude files that can be regenerated byte-for-byte from files that
// ARE tracked (page thumbnails / cover are pure deterministic resizes of the
// tracked page images). Everything else — narration audio, generated video,
// source PDF/text, captions, outline, AI image candidates — is an original
// input or the product of a non-deterministic process (TTS, LLM, AI image
// generation, external encoder versions), so it cannot be exactly reproduced
// and must be tracked in git to be restorable on another machine.
const GITIGNORE_CONTENT = [
  '*.thumb.jpg',
  'cover.jpg',
  'cover.thumb.jpg',
].join('\n') + '\n';

function gitOpts(dir: string) {
  return {
    cwd: dir,
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: GIT_USER_NAME,
      GIT_AUTHOR_EMAIL: GIT_USER_EMAIL,
      GIT_COMMITTER_NAME: GIT_USER_NAME,
      GIT_COMMITTER_EMAIL: GIT_USER_EMAIL,
    },
  };
}

async function git(dir: string, args: string[]): Promise<string> {
  const { stdout } = await execFile('git', args, gitOpts(dir));
  return stdout.trim();
}

/** Initialize a git repo inside the presentation storage directory if not already done. */
export async function ensurePresentationRepo(pdfId: string): Promise<void> {
  const dir = pdfDir(pdfId);
  const gitDir = path.join(dir, '.git');
  const gitignorePath = path.join(dir, '.gitignore');
  try {
    await fs.promises.access(gitDir, fs.constants.F_OK);
    await refreshGitignore(pdfId, dir, gitignorePath);
    return; // already initialized
  } catch {
    // not initialized yet
  }

  try {
    await execFile('git', ['init', '-b', 'main'], gitOpts(dir));
    await fs.promises.writeFile(gitignorePath, GITIGNORE_CONTENT, 'utf8');
    await execFile('git', ['add', '.gitignore'], gitOpts(dir));
    await execFile(
      'git',
      ['commit', '-m', 'chore: init presentation repository', '--allow-empty'],
      gitOpts(dir),
    );
  } catch (err) {
    logger.warn({ err, pdfId }, 'presentationGit: failed to init repo');
  }
}

/**
 * Keep an existing presentation repo's .gitignore in sync with GITIGNORE_CONTENT.
 * Older repos may have been created with a broader ignore list; rewriting it
 * here lets previously-excluded files (audio, video, source, captions, etc.)
 * become trackable on the next commit/push without recreating the repo.
 */
async function refreshGitignore(pdfId: string, dir: string, gitignorePath: string): Promise<void> {
  let current: string | null = null;
  try {
    current = await fs.promises.readFile(gitignorePath, 'utf8');
  } catch {
    current = null;
  }
  if (current === GITIGNORE_CONTENT) return;
  try {
    await fs.promises.writeFile(gitignorePath, GITIGNORE_CONTENT, 'utf8');
    await execFile('git', ['add', '.gitignore'], gitOpts(dir));
    const status = await git(dir, ['status', '--porcelain', '--', '.gitignore']);
    if (!status) return;
    await execFile(
      'git',
      ['commit', '-m', 'chore: update .gitignore', '--', '.gitignore'],
      gitOpts(dir),
    );
  } catch (err) {
    logger.warn({ err, pdfId }, 'presentationGit: failed to refresh .gitignore');
  }
}

/**
 * Stage and commit every change in the working tree (respecting .gitignore).
 * Used before pushing to GitHub so that files which only recently became
 * trackable (because the ignore list shrank) are included even though no
 * specific worker step calls commitPresentationFile for them.
 */
async function commitAllPendingChanges(pdfId: string, dir: string, message: string): Promise<void> {
  try {
    await execFile('git', ['add', '-A'], gitOpts(dir));
    const status = await git(dir, ['status', '--porcelain']);
    if (!status) return;
    await execFile('git', ['commit', '-m', message], gitOpts(dir));
  } catch (err) {
    logger.warn({ err, pdfId }, 'presentationGit: failed to commit pending changes');
  }
}

/**
 * Commit a file into the presentation's git repo.
 * `relPath` is relative to the presentation directory (e.g. "pages/001.jpg").
 */
export async function commitPresentationFile(
  pdfId: string,
  relPath: string,
  message: string,
): Promise<void> {
  const dir = pdfDir(pdfId);
  try {
    await ensurePresentationRepo(pdfId);
    await execFile('git', ['add', '--', relPath], gitOpts(dir));
    // Check if there is actually something to commit
    const status = await git(dir, ['status', '--porcelain', '--', relPath]);
    if (!status) return; // nothing changed
    await execFile('git', ['commit', '-m', message, '--', relPath], gitOpts(dir));
  } catch (err) {
    // Non-fatal: versioning failures must not break the main flow
    logger.warn({ err, pdfId, relPath }, 'presentationGit: commit failed');
  }
}

/**
 * Commit multiple files in a single commit.
 */
export async function commitPresentationFiles(
  pdfId: string,
  relPaths: string[],
  message: string,
): Promise<void> {
  if (relPaths.length === 0) return;
  const dir = pdfDir(pdfId);
  try {
    await ensurePresentationRepo(pdfId);
    await execFile('git', ['add', '--', ...relPaths], gitOpts(dir));
    const status = await git(dir, ['status', '--porcelain']);
    if (!status) return;
    await execFile('git', ['commit', '-m', message, '--', ...relPaths], gitOpts(dir));
  } catch (err) {
    logger.warn({ err, pdfId, relPaths }, 'presentationGit: multi-file commit failed');
  }
}

/**
 * Build an authenticated remote URL by embedding a personal access token
 * into an https GitHub repository URL (e.g. https://x-access-token:<token>@github.com/owner/repo.git).
 * Non-https URLs (e.g. git@github.com:...) are returned unchanged since tokens
 * cannot be embedded in the SSH form.
 */
export function buildAuthenticatedRepoUrl(repoUrl: string, token: string): string {
  const trimmedUrl = repoUrl.trim();
  const trimmedToken = token.trim();
  if (!trimmedToken) return trimmedUrl;
  try {
    const parsed = new URL(trimmedUrl);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return trimmedUrl;
    parsed.username = 'x-access-token';
    parsed.password = trimmedToken;
    return parsed.toString();
  } catch {
    return trimmedUrl;
  }
}

/**
 * Push a presentation's local git repository to a branch named after the
 * presentation id on the configured GitHub remote. Each presentation keeps
 * its own branch so multiple presentations can share a single repository.
 */
export async function pushPresentationToGitHub(
  pdfId: string,
  repoUrl: string,
  token: string,
): Promise<void> {
  const trimmedRepoUrl = repoUrl.trim();
  if (!trimmedRepoUrl) throw new Error('GitHub repository URL is not configured');

  const dir = pdfDir(pdfId);
  await ensurePresentationRepo(pdfId);
  await commitAllPendingChanges(pdfId, dir, 'sync: snapshot before GitHub push');
  const authenticatedUrl = buildAuthenticatedRepoUrl(trimmedRepoUrl, token);
  const branch = await git(dir, ['rev-parse', '--abbrev-ref', 'HEAD']);
  await execFile(
    'git',
    ['push', authenticatedUrl, `${branch}:refs/heads/${pdfId}`, '--force'],
    gitOpts(dir),
  );
}

export interface FileVersionEntry {
  hash: string;
  date: string;
  message: string;
}

/**
 * Return the git log for a specific file inside a presentation repo.
 * `relPath` is relative to the presentation directory.
 */
export async function getPresentationFileHistory(
  pdfId: string,
  relPath: string,
): Promise<FileVersionEntry[]> {
  const dir = pdfDir(pdfId);
  try {
    const out = await git(dir, [
      'log',
      '--follow',
      '--format=%H\x1f%aI\x1f%s',
      '--',
      relPath,
    ]);
    if (!out) return [];
    return out
      .split('\n')
      .filter(Boolean)
      .map((line) => {
        const [hash = '', date = '', ...rest] = line.split('\x1f');
        return { hash, date, message: rest.join('\x1f') };
      });
  } catch {
    return [];
  }
}

/**
 * Return the raw file content at a specific commit hash.
 * Suitable for binary (image) and text (script) files.
 */
export async function getPresentationFileAtCommit(
  pdfId: string,
  relPath: string,
  hash: string,
): Promise<Buffer> {
  const dir = pdfDir(pdfId);
  const { stdout } = await execFile(
    'git',
    ['show', `${hash}:${relPath}`],
    { ...gitOpts(dir), encoding: 'buffer' } as Parameters<typeof execFile>[2],
  );
  return stdout as unknown as Buffer;
}

/**
 * Restore a file in the working tree to the state at a given commit and
 * create a new commit recording the rollback.
 */
export async function restorePresentationFile(
  pdfId: string,
  relPath: string,
  hash: string,
  message: string,
): Promise<void> {
  const dir = pdfDir(pdfId);
  await ensurePresentationRepo(pdfId);
  // Write old version back to disk
  const content = await getPresentationFileAtCommit(pdfId, relPath, hash);
  const abs = path.join(dir, relPath);
  await fs.promises.mkdir(path.dirname(abs), { recursive: true });
  await fs.promises.writeFile(abs, content);
  // Commit the restore
  await execFile('git', ['add', '--', relPath], gitOpts(dir));
  const status = await git(dir, ['status', '--porcelain', '--', relPath]);
  if (!status) return; // already at that version
  await execFile('git', ['commit', '-m', message, '--', relPath], gitOpts(dir));
}
