import { z } from 'zod';
import type { ChatCompletionMessageParam } from 'openai/resources/chat/completions';
import { callChatJSON, streamChatText } from './openai';
import { findUnsafeScriptPattern } from './animationCustomScript';

/**
 * React slide pages (`render_type = 'react'`) — see docs/react-slide-design.md.
 *
 * A React slide is three artifacts that deliberately live apart from each other:
 *
 *  - the JSX source (`<uid>.slide.jsx`), written by the LLM or by hand;
 *  - its esbuild-compiled JS (`<uid>.slide.js`), the only thing the sandbox iframe executes;
 *  - a config (`<uid>.slide.json`) holding per-element text/CSS overrides and the background.
 *
 * Keeping the config out of the code is what makes "edit the text on the slide" survive a
 * regeneration of the code — and, conversely, what lets a user throw away their tweaks without
 * losing the layout. The deck-wide theme (design tokens) lives one level up, in
 * `slide-theme.json`, so restyling a whole presentation never touches a single page's code.
 *
 * Everything the browser will eventually evaluate passes through this module first: code goes
 * through `findUnsafeReactSlideCode()` (shared with the custom-script animation sandbox) and
 * every CSS value through `isSafeCssValue()`, so a page can never pull in an external resource
 * or reach the parent document.
 */

export const MAX_REACT_SLIDE_CODE_LENGTH = 60000;
export const MAX_REACT_SLIDE_PROMPT_LENGTH = 2000;
export const MAX_OVERRIDE_TEXT_LENGTH = 2000;
export const MAX_CSS_VALUE_LENGTH = 200;
export const MAX_OVERRIDE_ENTRIES = 200;
export const MAX_THEME_CUSTOM_CSS_LENGTH = 4000;

/** Design tokens a slide theme may define. Anything outside this list is dropped on load/save. */
export const SLIDE_THEME_TOKEN_KEYS = [
  '--slide-bg',
  '--slide-surface',
  '--slide-fg',
  '--slide-fg-muted',
  '--slide-accent',
  '--slide-accent-fg',
  '--slide-border',
  '--slide-font-heading',
  '--slide-font-body',
  '--slide-font-mono',
  '--slide-heading-size',
  '--slide-body-size',
  '--slide-radius',
  '--slide-gap',
  '--slide-padding',
  '--slide-shadow',
] as const;

export type SlideThemeTokenKey = (typeof SLIDE_THEME_TOKEN_KEYS)[number];

export const DEFAULT_SLIDE_THEME_TOKENS: Record<SlideThemeTokenKey, string> = {
  '--slide-bg': '#0f172a',
  '--slide-surface': '#1e293b',
  '--slide-fg': '#f8fafc',
  '--slide-fg-muted': '#94a3b8',
  '--slide-accent': '#38bdf8',
  '--slide-accent-fg': '#0f172a',
  '--slide-border': '#334155',
  '--slide-font-heading': '"Noto Sans TC", system-ui, sans-serif',
  '--slide-font-body': '"Noto Sans TC", system-ui, sans-serif',
  '--slide-font-mono': 'ui-monospace, monospace',
  '--slide-heading-size': '88px',
  '--slide-body-size': '36px',
  '--slide-radius': '24px',
  '--slide-gap': '32px',
  '--slide-padding': '96px',
  '--slide-shadow': '0 24px 60px rgba(0,0,0,0.35)',
};

/**
 * CSS properties the on-slide inspector may override, in kebab-case.
 *
 * Deliberately excludes anything that can pull in an external resource (`background-image`,
 * `content`, `filter`, `mask`, `cursor`): the sandbox has no network business, and a property
 * that accepts `url(...)` would be a way around that. Backgrounds have their own flow
 * (`ReactSlideConfig.background`) where the image is generated by us and served from our origin.
 */
export const EDITABLE_CSS_PROPERTIES = [
  'color',
  'background-color',
  'font-size',
  'font-weight',
  'font-family',
  'font-style',
  'line-height',
  'letter-spacing',
  'text-align',
  'text-transform',
  'text-shadow',
  'opacity',
  'padding',
  'margin',
  'border-radius',
  'border-width',
  'border-style',
  'border-color',
  'box-shadow',
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'display',
  'flex-direction',
  'justify-content',
  'align-items',
  'gap',
  'transform',
  'z-index',
] as const;

const EDITABLE_CSS_PROPERTY_SET: ReadonlySet<string> = new Set(EDITABLE_CSS_PROPERTIES);

/**
 * Values that could reach outside the sandbox or close the surrounding `<style>`/attribute.
 * `url(` covers remote images/fonts, `@import` remote stylesheets, `expression(` legacy IE
 * script, `javascript:` script URLs, and `<`/`}` markup or rule breakouts.
 */
const UNSAFE_CSS_VALUE = /url\s*\(|@import|expression\s*\(|javascript\s*:|<|\}|;/i;

export function isSafeCssValue(value: string): boolean {
  if (value.length === 0 || value.length > MAX_CSS_VALUE_LENGTH) return false;
  return !UNSAFE_CSS_VALUE.test(value);
}

export function isEditableCssProperty(property: string): boolean {
  return EDITABLE_CSS_PROPERTY_SET.has(property);
}

/**
 * Keep only overrides the sandbox is allowed to apply: known properties, safe values, and text
 * within the length cap. Invalid entries are dropped rather than rejected so one stale property
 * (e.g. saved by an older client) can't make a whole page unloadable.
 */
export function normalizeStyleOverrides(styles: Record<string, unknown> | undefined): Record<string, string> {
  const out: Record<string, string> = {};
  if (!styles) return out;
  for (const [rawProp, rawValue] of Object.entries(styles)) {
    const property = String(rawProp).trim().toLowerCase();
    if (!isEditableCssProperty(property)) continue;
    if (typeof rawValue !== 'string') continue;
    const value = rawValue.trim();
    if (!isSafeCssValue(value)) continue;
    out[property] = value;
  }
  return out;
}

/**
 * Element path assigned by the sandbox runtime: the chain of element-child indices from the
 * slide root, e.g. `0/2/1`. Element-only (text nodes are skipped) so it is insensitive to
 * whitespace, and computed at render time so the LLM never has to emit ids.
 */
const ELEMENT_PATH_RE = /^\d+(\/\d+)*$/;

export function isValidElementPath(path: string): boolean {
  return ELEMENT_PATH_RE.test(path) && path.length <= 200;
}

export interface ReactSlideOverride {
  text?: string;
  styles?: Record<string, string>;
}

export interface ReactSlideBackground {
  mode: 'none' | 'color' | 'image';
  color?: string;
  prompt?: string;
  /** Relative to the pdf storage dir, e.g. `pages/<uid>.slide-bg.png`. */
  file?: string;
  fit?: 'cover' | 'contain';
  position?: string;
  overlayColor?: string;
  overlayOpacity?: number;
}

export interface ReactSlideConfig {
  version: 1;
  prompt?: string;
  overrides: Record<string, ReactSlideOverride>;
  background: ReactSlideBackground;
  updated_at: string;
}

const CssColorSchema = z.string().trim().max(MAX_CSS_VALUE_LENGTH).refine(isSafeCssValue, 'unsafe css value');

const BackgroundSchema = z.object({
  mode: z.enum(['none', 'color', 'image']).default('none'),
  color: CssColorSchema.optional(),
  prompt: z.string().max(MAX_REACT_SLIDE_PROMPT_LENGTH).optional(),
  file: z.string().max(300).optional(),
  fit: z.enum(['cover', 'contain']).optional(),
  position: CssColorSchema.optional(),
  overlayColor: CssColorSchema.optional(),
  overlayOpacity: z.number().min(0).max(1).optional(),
});

const OverrideSchema = z.object({
  text: z.string().max(MAX_OVERRIDE_TEXT_LENGTH).optional(),
  styles: z.record(z.string(), z.unknown()).optional(),
});

export const ReactSlideConfigSchema = z.object({
  version: z.literal(1).default(1),
  prompt: z.string().max(MAX_REACT_SLIDE_PROMPT_LENGTH).optional(),
  overrides: z.record(z.string(), OverrideSchema).default({}),
  background: BackgroundSchema.default({ mode: 'none' }),
  updated_at: z.string().optional(),
});

export function defaultReactSlideConfig(): ReactSlideConfig {
  return { version: 1, overrides: {}, background: { mode: 'none' }, updated_at: new Date().toISOString() };
}

/**
 * Validate + normalize an incoming/stored config. Unknown element paths, unknown CSS properties
 * and unsafe values are dropped; a config that cannot be parsed at all falls back to the default
 * so a corrupted file renders an un-tweaked slide instead of breaking the page.
 */
export function sanitizeReactSlideConfig(input: unknown): ReactSlideConfig {
  const parsed = ReactSlideConfigSchema.safeParse(input);
  if (!parsed.success) return defaultReactSlideConfig();
  const overrides: Record<string, ReactSlideOverride> = {};
  let count = 0;
  for (const [path, value] of Object.entries(parsed.data.overrides)) {
    if (!isValidElementPath(path)) continue;
    if (count >= MAX_OVERRIDE_ENTRIES) break;
    const styles = normalizeStyleOverrides(value.styles as Record<string, unknown> | undefined);
    const text = typeof value.text === 'string' ? value.text : undefined;
    if (text === undefined && Object.keys(styles).length === 0) continue;
    overrides[path] = {
      ...(text !== undefined ? { text } : {}),
      ...(Object.keys(styles).length > 0 ? { styles } : {}),
    };
    count += 1;
  }
  const bg = parsed.data.background;
  return {
    version: 1,
    ...(parsed.data.prompt ? { prompt: parsed.data.prompt } : {}),
    overrides,
    background: {
      mode: bg.mode,
      ...(bg.color ? { color: bg.color } : {}),
      ...(bg.prompt ? { prompt: bg.prompt } : {}),
      ...(bg.file ? { file: bg.file } : {}),
      ...(bg.fit ? { fit: bg.fit } : {}),
      ...(bg.position ? { position: bg.position } : {}),
      ...(bg.overlayColor ? { overlayColor: bg.overlayColor } : {}),
      ...(bg.overlayOpacity !== undefined ? { overlayOpacity: bg.overlayOpacity } : {}),
    },
    updated_at: parsed.data.updated_at ?? new Date().toISOString(),
  };
}

export function parseStoredReactSlideConfig(raw: string): ReactSlideConfig {
  try {
    return sanitizeReactSlideConfig(JSON.parse(raw));
  } catch {
    return defaultReactSlideConfig();
  }
}

export interface SlideTheme {
  version: 1;
  name: string;
  tokens: Record<SlideThemeTokenKey, string>;
  customCss?: string;
  updated_at: string;
}

export function defaultSlideTheme(): SlideTheme {
  return {
    version: 1,
    name: 'Default',
    tokens: { ...DEFAULT_SLIDE_THEME_TOKENS },
    updated_at: new Date().toISOString(),
  };
}

const SlideThemeSchema = z.object({
  version: z.literal(1).default(1),
  name: z.string().trim().min(1).max(80).default('Default'),
  tokens: z.record(z.string(), z.unknown()).default({}),
  customCss: z.string().max(MAX_THEME_CUSTOM_CSS_LENGTH).optional(),
  updated_at: z.string().optional(),
});

/**
 * Custom CSS is injected into the sandbox verbatim, so it gets a coarser check than token values
 * (which are single declarations): only the constructs that reach outside the sandbox or escape
 * the `<style>` element are rejected. Braces and semicolons are legitimate here.
 */
const UNSAFE_CUSTOM_CSS = /url\s*\(|@import|expression\s*\(|javascript\s*:|<\s*\/?\s*script/i;

export function sanitizeSlideTheme(input: unknown): SlideTheme {
  const parsed = SlideThemeSchema.safeParse(input);
  if (!parsed.success) return defaultSlideTheme();
  const tokens: Record<SlideThemeTokenKey, string> = { ...DEFAULT_SLIDE_THEME_TOKENS };
  for (const key of SLIDE_THEME_TOKEN_KEYS) {
    const value = parsed.data.tokens[key];
    if (typeof value !== 'string') continue;
    const trimmed = value.trim();
    if (!isSafeCssValue(trimmed)) continue;
    tokens[key] = trimmed;
  }
  const customCss = typeof parsed.data.customCss === 'string' ? parsed.data.customCss : undefined;
  const safeCustomCss = customCss && !UNSAFE_CUSTOM_CSS.test(customCss) ? customCss : undefined;
  return {
    version: 1,
    name: parsed.data.name,
    tokens,
    ...(safeCustomCss ? { customCss: safeCustomCss } : {}),
    updated_at: parsed.data.updated_at ?? new Date().toISOString(),
  };
}

export function parseStoredSlideTheme(raw: string): SlideTheme {
  try {
    return sanitizeSlideTheme(JSON.parse(raw));
  } catch {
    return defaultSlideTheme();
  }
}

/**
 * Static safety check on slide code, sharing the custom-script animation's deny list (fetch,
 * XMLHttpRequest, WebSocket, import(), require(), eval, Function(), cookies, storage,
 * window.parent/top, frameElement) and adding the ES-module forms a JSX file can carry.
 *
 * The sandbox already blocks all of this at the browser level; this exists so obviously unsafe
 * code is rejected before it is ever stored, and so the user gets a specific reason instead of a
 * blank slide.
 */
export function findUnsafeReactSlideCode(code: string): string | null {
  if (/^\s*import\s+[^(]/m.test(code)) return 'import';
  if (/^\s*export\s+/m.test(code)) return 'export';
  return findUnsafeScriptPattern(code);
}

/** The contract the sandbox expects: a component exported through `window.SlideComponent`. */
export function findReactSlideContractIssue(code: string): string | null {
  if (!/window\s*\.\s*SlideComponent\s*=|window\s*\[\s*['"]SlideComponent['"]\s*\]\s*=/.test(code)) {
    return 'Generated code must assign the component to window.SlideComponent';
  }
  return null;
}

/**
 * Pull the code out of an LLM reply. Prefers a fenced block (```jsx / ```js / ```), because
 * models habitually wrap code even when told not to, and falls back to the raw text so a
 * well-behaved reply still works.
 */
export function extractJsxFromLlmOutput(output: string): string {
  const fenced = /```(?:jsx?|tsx?|javascript|react)?\s*\n([\s\S]*?)```/i.exec(output);
  const code = fenced ? (fenced[1] ?? '') : output;
  return code.trim();
}

export interface CompiledReactSlide {
  code: string;
  warnings: string[];
}

/**
 * Compile JSX to browser-ready JS with esbuild (`React.createElement` factory — the sandbox has
 * React as a global, not as a module).
 *
 * esbuild is imported dynamically so a runtime that shipped without it fails here with a clear
 * message at save time, rather than storing code that would only break once a viewer opens the
 * page. Compile errors are surfaced verbatim: they are the user's own syntax errors and the only
 * useful thing we can say about them.
 */
export async function compileReactSlide(source: string): Promise<CompiledReactSlide> {
  let transform: typeof import('esbuild').transform;
  try {
    ({ transform } = await import('esbuild'));
  } catch {
    throw new Error('JSX compiler (esbuild) is unavailable in this runtime');
  }
  const result = await transform(source, {
    loader: 'jsx',
    jsx: 'transform',
    jsxFactory: 'React.createElement',
    jsxFragment: 'React.Fragment',
    target: 'es2018',
    format: 'iife',
  });
  return { code: result.code, warnings: result.warnings.map((w) => w.text) };
}

export interface ReactSlideValidation {
  ok: boolean;
  /** Human-readable reason, already safe to show the user. */
  message?: string;
  compiled?: string;
}

/** Full save-time pipeline: length → deny list → contract → compile. */
export async function validateAndCompileReactSlide(source: string): Promise<ReactSlideValidation> {
  const code = source.trim();
  if (code.length === 0) return { ok: false, message: 'Slide code is empty' };
  if (code.length > MAX_REACT_SLIDE_CODE_LENGTH) {
    return { ok: false, message: `Slide code exceeds ${MAX_REACT_SLIDE_CODE_LENGTH} characters` };
  }
  const unsafe = findUnsafeReactSlideCode(code);
  if (unsafe) return { ok: false, message: `Slide code uses a disallowed API: ${unsafe}` };
  const contract = findReactSlideContractIssue(code);
  if (contract) return { ok: false, message: contract };
  try {
    const compiled = await compileReactSlide(code);
    return { ok: true, compiled: compiled.code };
  } catch (err) {
    return { ok: false, message: err instanceof Error ? err.message : String(err) };
  }
}

/** The starting point offered for a page that isn't a React slide yet. */
export function defaultReactSlideCode(): string {
  return `function Slide() {
  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        gap: 'var(--slide-gap)',
        padding: 'var(--slide-padding)',
        boxSizing: 'border-box',
        fontFamily: 'var(--slide-font-body)',
        color: 'var(--slide-fg)',
      }}
    >
      <h1 style={{ margin: 0, fontFamily: 'var(--slide-font-heading)', fontSize: 'var(--slide-heading-size)' }}>
        標題
      </h1>
      <p style={{ margin: 0, fontSize: 'var(--slide-body-size)', color: 'var(--slide-fg-muted)' }}>
        用一句話描述這一頁要講的重點。
      </p>
    </div>
  );
}

window.SlideComponent = Slide;
`;
}

export interface ReactSlideGenerationInput {
  prompt: string;
  pageText?: string;
  pageScript?: string;
  currentCode?: string;
  theme: SlideTheme;
}

/**
 * The rules the generated component must follow. Written as hard constraints rather than advice
 * because each one maps to a way the page would otherwise break: no imports (nothing resolves in
 * the sandbox), no post-mount mutation (per-element overrides are applied once after render, so a
 * component that rewrites itself would erase them), tokens instead of literal colors (that is what
 * makes a deck-wide theme mean anything), and a 1920×1080 canvas (the frame scales, it does not
 * reflow).
 */
export function buildReactSlideSystemPrompt(theme: SlideTheme): string {
  const tokenList = SLIDE_THEME_TOKEN_KEYS.map((key) => `${key}: ${theme.tokens[key]}`).join('\n');
  return [
    '你是一位簡報設計工程師，負責用 React 撰寫一頁投影片。',
    '',
    '硬性規則：',
    '1. 只輸出一段 JSX 程式碼，用 ```jsx 圍籬包住，圍籬外不要有任何說明文字。',
    '2. 定義 `function Slide() { ... }`，最後一行必須是 `window.SlideComponent = Slide;`。',
    '3. 只能使用全域的 `React` 與 JSX。不可以 import / require / export，不可以 fetch、計時器、localStorage 或任何外部資源（含外部圖片網址與字型）。',
    '4. 元件必須是靜態的：掛載後不可再改寫自己的內容（畫面上的文字與樣式之後會由使用者的覆寫設定套用）。',
    '5. 版面固定為 1920×1080 的畫布，根節點請用 `width: \'100%\', height: \'100%\'`、`boxSizing: \'border-box\'`，不需要 responsive 寫法。',
    '6. 樣式只能用 inline `style={{...}}`（必要時可加一個 `<style>` 區塊），不可以使用 Tailwind 或任何 class library。',
    '7. 顏色、字體、字級、圓角、間距一律使用主題變數（例如 `var(--slide-accent)`），不要寫死色碼。',
    '8. 不要在元件內畫滿版底色，背景由外層負責。',
    '9. 投影片是「要點」不是逐字稿：文字精簡，一頁最多 6 個重點，字級要在 3 公尺外看得清楚。',
    '',
    '可用的主題變數：',
    tokenList,
  ].join('\n');
}

export function buildReactSlideMessages(input: ReactSlideGenerationInput): ChatCompletionMessageParam[] {
  const parts: string[] = [`使用者的描述：\n${input.prompt.trim()}`];
  if (input.pageScript?.trim()) {
    parts.push(`這一頁的逐字稿（投影片內容要與它呼應，但不要照抄）：\n${input.pageScript.trim().slice(0, 3000)}`);
  }
  if (input.pageText?.trim()) {
    parts.push(`這一頁原始頁面的文字（可作為事實依據）：\n${input.pageText.trim().slice(0, 3000)}`);
  }
  if (input.currentCode?.trim()) {
    parts.push(`目前這一頁的程式碼（請在此基礎上修改，保留使用者沒有要求變動的部分）：\n${input.currentCode.trim().slice(0, 8000)}`);
  }
  return [
    { role: 'system', content: buildReactSlideSystemPrompt(input.theme) },
    { role: 'user', content: parts.join('\n\n') },
  ];
}

/**
 * Ask the LLM for the page's React code and return it compiled. One retry is spent when the first
 * attempt fails validation, with the reason fed back to the model — the common failures (forgot
 * the `window.SlideComponent` line, a stray import, a JSX typo) are exactly the kind a model fixes
 * when told what broke.
 */
export async function generateReactSlideCode(
  input: ReactSlideGenerationInput,
): Promise<{ code: string; compiled: string }> {
  const messages = buildReactSlideMessages(input);
  let lastMessage = 'unknown error';
  for (let attempt = 0; attempt < 2; attempt += 1) {
    let output = '';
    await streamChatText({
      label: 'generate_react_slide',
      messages,
      maxTokens: 4000,
      temperature: 0.4,
      onDelta: (delta) => {
        output += delta;
      },
    });
    const code = extractJsxFromLlmOutput(output);
    const validation = await validateAndCompileReactSlide(code);
    if (validation.ok && validation.compiled) {
      return { code, compiled: validation.compiled };
    }
    lastMessage = validation.message ?? 'unknown error';
    messages.push({ role: 'assistant', content: output.slice(0, 8000) });
    messages.push({
      role: 'user',
      content: `上一次的程式碼無法使用，原因：${lastMessage}。請修正後重新輸出完整程式碼（同樣用 \`\`\`jsx 圍籬包住）。`,
    });
  }
  throw new Error(`React slide generation failed: ${lastMessage}`);
}

const GeneratedThemeSchema = z.object({
  name: z.string().min(1).max(80),
  tokens: z.record(z.string(), z.string()),
});

/**
 * Generate a deck-wide theme from one sentence. The model only ever returns token values, never
 * CSS rules — the token list is fixed, so a theme can restyle every page without being able to
 * inject anything the sandbox would have to evaluate.
 */
export async function generateSlideTheme(prompt: string, deckTitle?: string): Promise<SlideTheme> {
  const result = await callChatJSON({
    label: 'generate_slide_theme',
    schema: GeneratedThemeSchema,
    maxTokens: 1200,
    temperature: 0.6,
    messages: [
      {
        role: 'system',
        content: [
          '你是一位簡報視覺設計師，負責產生一組簡報主題設計變數。',
          '只回傳 JSON：{"name":"主題名稱","tokens":{"--slide-bg":"...", ...}}。',
          `tokens 只能包含這些鍵（全部都要給值）：${SLIDE_THEME_TOKEN_KEYS.join('、')}。`,
          '色彩用 #rrggbb；字體用 CSS font-family 字串（只能用系統字體或 "Noto Sans TC"，不可引用外部字型）；',
          '尺寸用 px（畫布是 1920×1080，標題級距通常 72~120px、內文 28~44px）；陰影用 box-shadow 語法。',
          '值裡不可以出現 url()、@import、分號或角括號。',
          '請確保前景色與背景色的對比足夠（投影機上仍看得清楚）。',
        ].join('\n'),
      },
      {
        role: 'user',
        content: deckTitle ? `簡報主題：${deckTitle}\n\n風格描述：${prompt}` : `風格描述：${prompt}`,
      },
    ],
  });
  return sanitizeSlideTheme({ version: 1, name: result.data.name, tokens: result.data.tokens });
}

/**
 * Prompt used for background-image generation. The instructions exist because a background is not
 * a picture: anything with its own text, a busy centre, or a palette that fights the theme makes
 * the slide's actual content unreadable — and the model will happily produce all three otherwise.
 */
export function buildBackgroundImagePrompt(prompt: string, theme: SlideTheme): string {
  return [
    'A 16:9 presentation slide BACKGROUND image.',
    'Absolutely no text, letters, numbers, logos or watermarks anywhere in the image.',
    'Keep the central area calm and low-contrast so overlaid headline text stays readable;',
    'place any visual interest toward the edges and corners.',
    `Harmonize with this color palette: background ${theme.tokens['--slide-bg']}, accent ${theme.tokens['--slide-accent']}.`,
    'Subtle, professional, uncluttered.',
    '',
    `Subject / mood requested by the user: ${prompt.trim()}`,
  ].join(' ');
}
