import type { ApiError } from './types';

export const ERROR_CODE = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_UPLOAD_TYPE: 'INVALID_UPLOAD_TYPE',
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_URL: 'INVALID_URL',
  API_KEY_MISSING: 'API_KEY_MISSING',
  MODEL_QUOTA_EXCEEDED: 'MODEL_QUOTA_EXCEEDED',
  MODEL_UNAVAILABLE: 'MODEL_UNAVAILABLE',
  PDF_NOT_FOUND: 'PDF_NOT_FOUND',
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVALID_STATE: 'INVALID_STATE',
  JOB_CONFLICT: 'JOB_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE] | string;

const LEGACY_TO_STANDARD: Record<string, ErrorCode> = {
  NO_FILE: ERROR_CODE.FILE_REQUIRED,
  INVALID_MIME: ERROR_CODE.INVALID_UPLOAD_TYPE,
  INVALID_YOUTUBE_URL: ERROR_CODE.INVALID_URL,
  JOB_ALREADY_RUNNING: ERROR_CODE.JOB_CONFLICT,
  JOB_NOT_ACTIVE: ERROR_CODE.JOB_CONFLICT,
  COVER_NOT_READY: ERROR_CODE.RESOURCE_NOT_FOUND,
  VIDEO_NOT_FOUND: ERROR_CODE.RESOURCE_NOT_FOUND,
  OUTLINE_NOT_FOUND: ERROR_CODE.RESOURCE_NOT_FOUND,
  PAGE_IMAGE_NOT_FOUND: ERROR_CODE.RESOURCE_NOT_FOUND,
  PAGE_TEXT_NOT_FOUND: ERROR_CODE.RESOURCE_NOT_FOUND,
  PAGE_SCRIPT_NOT_FOUND: ERROR_CODE.RESOURCE_NOT_FOUND,
  PAGE_AUDIO_NOT_FOUND: ERROR_CODE.RESOURCE_NOT_FOUND,
};

export function normalizeErrorCode(code: string): ErrorCode {
  return LEGACY_TO_STANDARD[code] ?? code;
}

export function apiError(code: string, message: string, detail?: unknown): ApiError & { detail?: unknown } {
  const normalized = normalizeErrorCode(code);
  return detail === undefined
    ? { error: { code: normalized, message } }
    : { error: { code: normalized, message }, detail };
}

